name: "Test"

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test action

    steps:
      - uses: actions/checkout@v4
        name: Checkout

      - name: Install dependencies
        run: npm install && npm i -g @vercel/ncc
        
      - name: Build
        run: npm run build

      - name: eslint
        run: npx eslint

      - name: Ensure no pending Git changes
        run: |
          GIT_STATUS=$(git status --porcelain)
          if [[ -n $GIT_STATUS ]]; then
            echo "There are pending Git changes after running the build. Did you forget to commit the .js files?"
            echo "$GIT_STATUS"
            exit 1
          fi

      - name: Run tests
        run: npm run test

      - name: Load test key
        id: get_key
        run: |
          value=$(cat src/tests/test_key_b64.txt)
          echo "text=$value" >> $GITHUB_OUTPUT

      - uses: ./
        name: zipalign and Sign APK
        with:
          releaseDirectory: src/tests/apk-zip
          signingKeyBase64: ${{ steps.get_key.outputs.text }}
          alias: test_key
          keyStorePassword: android
          keyPassword: android
          zipAlign: true

      - uses: ./
        name: Sign APK
        with:
          releaseDirectory: src/tests/apk
          signingKeyBase64: ${{ steps.get_key.outputs.text }}
          alias: test_key
          keyStorePassword: android
          keyPassword: android

      - uses: ./
        name: Sign AAB
        with:
          releaseDirectory: src/tests/aab
          signingKeyBase64: ${{ steps.get_key.outputs.text }}
          alias: test_key
          keyStorePassword: android
          keyPassword: android
