name: "Tag & Deploy Action"

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test action

    steps:
      - uses: actions/checkout@v3
        name: Checkout code

      - name: Run tests
        run: npm run test

      - uses: pCYSl5EDgo/cat@1.0.0
        name: Cat for GitHub Actions
        id: get_key
        with:
          path: __tests__/test_key_b64.txt

      - uses: ./
        name: Zipalign and Sign APK
        with:
          releaseDirectory: __tests__/apk-zip
          signingKeyBase64: ${{ steps.get_key.outputs.text }}
          alias: test_key
          keyStorePassword: android
          keyPassword: android
          zipAlign: true

      - uses: ./
        name: Sign APK
        with:
          releaseDirectory: __tests__/apk
          signingKeyBase64: ${{ steps.get_key.outputs.text }}
          alias: test_key
          keyStorePassword: android
          keyPassword: android

      - uses: ./
        name: Sign AAB
        with:
          releaseDirectory: __tests__/aab
          signingKeyBase64: ${{ steps.get_key.outputs.text }}
          alias: test_key
          keyStorePassword: android
          keyPassword: android
